{% set name = "jupyterlab-geojson" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/jupyter-renderers/archive/refs/tags/@jupyterlab/geojson-extension@3.3.1.tar.gz
  sha256: 97d866920866098cd9c53835843a6f444dd5766a8e5e8cb8919b28e9874c7e08

build:
  number: 0
  # jupyterlab is missing on s390x
  skip: true  # [py<36 or (linux and s390x)]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - jupyter-packaging 0.7.9
    - jupyterlab 3.4.4
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/geojson-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\geojson-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: GeoJSON renderer for JupyterLab
  description: |
    This package provides a GeoJSON renderer for JupyterLab.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension
  doc_url: https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
