{% set name = "jupyterlab-geojson" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_geojson-{{ version }}.tar.gz
  sha256: cc7f6015f75f7816240402880134cd7174af64fbef010b1556071729f98a291f

build:
  number: 0
  # jupyterlab is missing on s390x
  skip: true  # [py<38 or (linux and s390x)]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5.0
    - hatch-nodejs-version
  run:
    - python
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_geojson
  requires:
    - pip
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/geojson-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\geojson-extension\\package.json (exit 0) else (exit 1)         # [win]

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: GeoJSON renderer for JupyterLab
  description: |
    This package provides a GeoJSON renderer for JupyterLab.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension
  doc_url: https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/geojson-extension

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
